### ISSUE TITLE
Configuring the component fails with Failed to connect: This third-party application does not exist in the system

### ISSUE THREAD

**Issue by rutgerhendriks** [PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring#1]
I'm running the latest home assistant docker image, 2023.3.3 (but had the same behaviour with 2023.1.7)
I've unzipped the 1.0.3 zip file into custom_components as per the installation instruction.
After a restart Home Assistant shows the custom component, so far so good
But when I try to add the integration and give:
app id - that's my username in the Android app right?
app secret - my password in the Android app
beehive id - shown in the Android app

I get the error:
Failed to connect: This third-party application does not exist in the system

I have no idea what that error means and I can't find it online.. Am I doing something wrong?

**Comment by majdzik84** [comment]
Hi. For the App ID and App Secret, write to the manufacturer :  service@gnetek.com

**Comment by PiotrMachowski** [comment]
Thanks @majdzik84, I'll add this info to README
