### ISSUE TITLE
Problem with add integration, 

### ISSUE THREAD

**Issue by ok1vkt** [PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring#3]
Hi, please can you help me.... I try your integrations.... If I add new integration, I must fill App ID, App Secret, beehjve ID..... I fill this, and I see this error:
Failed to connect: This third-party application does not exist in the system.

Can you help me with it? Thanks

**Comment by ok1vkt** [comment]
In Log, I have this errors...:

ELECTRIC_CURRENT_AMPERE was used from gne_pv_monitoring, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring/issues
ELECTRIC_POTENTIAL_VOLT was used from gne_pv_monitoring, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring/issues
ENERGY_KILO_WATT_HOUR was used from gne_pv_monitoring, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring/issues
POWER_WATT was used from gne_pv_monitoring, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring/issues
TEMP_CELSIUS was used from gne_pv_monitoring, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring/issues

**Comment by PiotrMachowski** [comment]
These are just warnings, you can ignore them

**Comment by ok1vkt** [comment]
OK, but why I cant connect with some third party applications? What it is mean? I need some next application? 

And I ask you, the values as App ID, App Secret, beehjve ID. Is it my login (user name and password) on web site? BeehiveID I know. Is it true? Or AppID is some different?
Thanks

**Comment by PiotrMachowski** [comment]
Yes, they are different. You have to ask manufacturer to send them to you

https://github.com/PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring?tab=readme-ov-file#credentials

**Comment by ok1vkt** [comment]
OK thanks.... I ask them. And how this parameters called? What I need from they.
But I am not sure about reply. Because I write him about RS485 registers, to read informations from Beehive directly.... And no respons :-(

**Comment by PiotrMachowski** [comment]
https://github.com/PiotrMachowski/Home-Assistant-custom-components-GNE-PV-Monitoring/issues/1
